/* Cinematic homepage and time capsule. Shared pages remain in pages.js. */
(() => {
  'use strict';
  const e=Sarah.utils.escape, ui=Sarah.ui, content=SARAH_CONTENT.experience;
  const photo=id=>SARAH_CONTENT.media.find(m=>m.id===id)||SARAH_CONTENT.media[0];
  const rose=()=>`<svg class="bloom-rose" viewBox="0 0 100 100" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1"><ellipse cx="50" cy="42" rx="14" ry="27"/><ellipse cx="50" cy="42" rx="14" ry="27" transform="rotate(60 50 42)"/><ellipse cx="50" cy="42" rx="14" ry="27" transform="rotate(120 50 42)"/><circle cx="50" cy="42" r="10"/><path d="M50 65v32M50 82q-20-22-29-8q11 15 29 8M50 87q20-23 29-11q-8 16-29 11"/></g></svg>`;
  const sectionHead=(n,label,title,text='')=>`<div class="cinema-heading reveal"><p class="eyebrow"><span>${n}</span> ${label}</p><h2>${title}</h2>${text?`<p class="lead">${text}</p>`:''}</div>`;
  const days=()=>content.days.map(d=>`<a class="day-poster" href="#/day/${d.day.toLowerCase()}"><img src="${e(photo(d.image).src)}" alt="${e(photo(d.image).alt)}" loading="lazy"><span class="poster-date"><b>${d.date}</b><small>${d.month} · ${d.day.toUpperCase()}</small></span><span class="poster-bottom"><small>${d.theme}</small><h3>${d.title}</h3><p>${d.text}</p><span class="poster-link">Explore ${d.day} <b aria-hidden="true">↗</b></span></span></a>`).join('');
  const capsuleMarkup=c=>`<div class="capsule-copy"><p class="eyebrow">${e(c.label)}</p><h3>${e(c.title)}</h3><p class="capsule-place">${e(c.place)} · ${e(c.year)}</p><p>${e(c.text)}</p><div class="button-row">${c.chapter?`<a class="button" href="#/journey/${c.chapter}">Open this chapter ${ui.icon('arrow')}</a>`:`<a class="button" href="#/memories/share?decade=${c.decade}">Add a memory from these years ${ui.icon('arrow')}</a>`}<a class="text-link" href="#/chamber/${c.decade}">Enter the ${c.decade} gallery ↗</a></div></div><div class="capsule-context"><span class="capsule-year" aria-hidden="true">${c.decade.slice(0,4)}</span>${c.history?`<img src="${e(SARAH_CONTENT.history.find(h=>h.id===c.history).src)}" alt="${e(SARAH_CONTENT.history.find(h=>h.id===c.history).alt)}"><small>HISTORICAL CONTEXT · NOT A FAMILY PHOTO</small>`:`${rose()}<small>${c.chapter?'A CHAPTER IN SARAH’S STORY':'AN OPEN CHAPTER'}</small>`}<p>${e(c.context)}</p>${c.history?`<a class="text-link" href="${e(SARAH_CONTENT.history.find(h=>h.id===c.history).url)}" target="_blank" rel="noopener noreferrer">Read the historical source ↗</a>`:''}</div>`;
  const timeline=()=>`<div class="time-capsule reveal"><div class="capsule-nav"><button class="icon-button" data-era-step="-1" aria-label="Previous decade">←</button><div class="era-track" role="tablist" aria-label="Choose a decade">${content.capsules.map((c,i)=>`<button id="era-${c.decade}" role="tab" aria-selected="${i===0}" tabindex="${i===0?0:-1}" aria-controls="capsule-panel" data-era="${i}">${c.decade}</button>`).join('')}</div><button class="icon-button" data-era-step="1" aria-label="Next decade">→</button></div><div id="capsule-panel" class="capsule-scene roots" role="tabpanel" aria-labelledby="era-1930s">${capsuleMarkup(content.capsules[0])}</div><p class="capsule-hint">Swipe the years or use the arrows. Each decade opens another door.</p></div>`;
  const galleries=()=>`<div class="gallery-shelf reveal"><a class="gallery-ticket ticket-feature" href="#/chamber/all"><img src="${e(photo('img_1222').src)}" alt="Sarah in purple at an outdoor family gathering" loading="lazy"><div><span class="play-medallion">${ui.icon('play')}</span><small>THE SIGNATURE EXPERIENCE</small><h3>A walk through<br>our memories.</h3><p>${SARAH_CONTENT.media.length} photographs · A floating family gallery</p><span>Enter the experience ↗</span></div></a><a class="gallery-ticket ticket-shuffle" href="#/chamber/shuffle"><img src="${e(photo('family-08').src)}" alt="${e(photo('family-08').alt)}" loading="lazy"><div><span class="play-medallion">${ui.icon('shuffle')}</span><small>A LITTLE SURPRISE</small><h3>Sarah Shuffle.</h3><p>Every photo. A different order.</p><span>Let the memories play ↗</span></div></a></div><div class="shelf-label"><span>OR CHOOSE A DECADE</span><span>Swipe to explore →</span></div><div class="decade-shelf">${content.capsules.map((c,i)=>`<a class="decade-ticket era-${i}" href="#/chamber/${c.decade}"><span>${c.decade}</span><small>${c.decade==='2010s'?'2 dated family photos':c.history?'History & an open family chapter':'Help complete this chapter'}</small><b aria-hidden="true">↗</b></a>`).join('')}<a class="decade-ticket undated-ticket" href="#/chamber/undated"><span>Undated</span><small>Help place a moment in time</small><b aria-hidden="true">↗</b></a></div><p class="copy-note shelf-note">Most family photographs are still being dated. They live in the full and undated collections until the family confirms their years.</p>`;
  Sarah.pages.home=()=>`<section class="birthday-hero"><img class="hero-full-photo" src="${photo('img_1222').src}" alt="${e(photo('img_1222').alt)}" fetchpriority="high"><div class="hero-wash"></div><div class="petals" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="birthday-hero-copy"><p class="eyebrow">YOU’RE INVITED · TUCSON, ARIZONA</p><div class="birthday-wordmark">Mother Sarah <span>Eldridge</span></div><h1>90 years.<br><em>And the party<br>is just beginning.</em></h1><p class="hero-invite">Come celebrate Sarah’s 90th birthday <strong>with her.</strong><br>October 2–4, 2026 · A whole weekend together.</p><div class="button-row"><button class="button light" data-jump="weekend">Explore the birthday weekend ${ui.icon('arrow')}</button><button class="hero-secondary" data-jump="meet-sarah">Meet the birthday girl ↓</button></div></div><div class="hero-bottom"><span>FAITH. FAMILY. A LITTLE TOUCH OF RED.</span><button data-jump="weekend" aria-label="Scroll to the birthday weekend">SCROLL TO CELEBRATE <span>↓</span></button></div><div class="hero-corner-mark" aria-hidden="true">90<span>HAPPY BIRTHDAY</span></div></section>
<section id="weekend" class="cinema-section wrap">${sectionHead('01','The birthday weekend','Three days together.<br><em>So many new memories.</em>','Come for the hugs. Stay for the stories. From a Friday welcome to Saturday’s birthday party and Sunday fellowship, there’s a place for you all weekend.')}<div class="event-posters reveal">${days()}</div><div class="section-under"><p>October 2–4, 2026 · Tucson local time<br><small>Sarah’s birthday is Monday, October 5. Card imagery is from the family album.</small></p><a class="text-link" href="#/events">All events & calendar details ${ui.icon('arrow')}</a></div></section>
<section id="meet-sarah" class="bio-feature cinema-section"><div class="wrap feature-split"><div class="portrait-stack reveal"><img src="${photo('img_0961').src}" alt="${e(photo('img_0961').alt)}" loading="lazy"><span class="portrait-label">Love, with a personality.</span>${rose()}</div><div class="split-copy reveal"><p class="eyebrow">02 · MEET THE BIRTHDAY GIRL</p><h2>A quick wit.<br>A generous heart.<br><em>Entirely Sarah.</em></h2><p>She loves her family. She means what she says. And if she offers you sweet potatoes, you might want to ask how they’re prepared.</p><p>From a girl who loved reading in Texas to a mother of ten and the heart of so many family stories, Sarah brings faith, humor, and practical kindness to the people around her.</p><blockquote>“If I say I love you,<br>then I love you.”<cite>A favorite Sarah saying, shared by her family</cite></blockquote><a class="button" href="#/bio">Read Sarah’s story ${ui.icon('book')}</a></div></div></section>
<section id="love-story" class="cinema-section wrap"><div class="feature-split romance-split"><div class="split-copy reveal"><p class="eyebrow">03 · SARAH & JONAS</p><h2>He had a destination.<br><em>Life had other plans.</em></h2><p>A car that wouldn’t go any farther. Work in the Arizona cotton fields. A young woman with a mind of her own.</p><p>Before ten children and generations of family stories, there were two people whose roads unexpectedly crossed.</p><p class="story-disclosure">An artistic retelling inspired by family accounts. It captures the feeling and circumstances of their beginning; reconstructed scenes are not a historical transcript.</p><a class="button" href="#/sarah-and-jonas">Step into their story ${ui.icon('arrow')}</a></div><a href="#/sarah-and-jonas" class="romance-poster reveal" aria-label="Read The Road Between Us, Sarah and Jonas’s love story"><img src="${photo('img_1575').src}" alt="${e(photo('img_1575').alt)}" loading="lazy"><div class="poster-grain"></div><span class="romance-overline">SARAH & JONAS · A FAMILY LOVE STORY</span><div class="romance-title"><span>The Road</span><em>Between Us</em><small>SOMETIMES THE DETOUR IS THE BEGINNING.</small></div><span class="romance-credit">Original family album · Artistic retelling</span></a></div></section>
<section id="time-capsule" class="timeline-section cinema-section"><div class="wrap">${sectionHead('04','The interactive time capsule','Ninety years.<br><em>A world of stories.</em>','Move through the decades. Meet the girl, the young woman, the mother—and the changing world around her. Some chapters are waiting for your memories.')}${timeline()}</div></section>
<section id="photo-journeys" class="cinema-section wrap">${sectionHead('05','Choose your photo journey','Step inside<br><em>the family album.</em>','A familiar face floats into view. A moment comes back. Explore at your own pace, and tell us the stories only you know.')}${galleries()}<div class="section-under"><p>Pause anywhere. Look closer. Add a name, a date, a memory.</p><a class="text-link" href="#/explore">Prefer a simple gallery? ${ui.icon('photos')}</a></div></section>
<section id="birthday-love" class="contribute-feature cinema-section"><div class="wrap contribute-grid"><div class="reveal">${rose()}<p class="eyebrow">06 · YOU’RE PART OF THE STORY</p><h2>Send Sarah<br><em>some birthday love.</em></h2><p>A birthday wish. A photograph. That story everyone still laughs about. Bring it to the celebration.</p><div class="button-row"><a class="button" href="#/memories/share">Leave a wish or add photos ${ui.icon('heart')}</a><a class="text-link" href="#/memories">Read family stories ↗</a></div><p class="copy-note">Contributions go to the family by email for review before publication.</p></div><div class="birthday-note reveal"><span>Dear Sarah,</span><p>Here’s to more laughter,<br>more hugs,<br>and more memories<br>together.</p><small>WITH LOVE, YOUR FAMILY & FRIENDS</small></div></div></section>`;
  const biography=()=>`<article class="biography-page narrow page-bottom"><a class="back-link" href="#/home?section=meet-sarah">← Back to the birthday weekend</a>${ui.heading('Meet Mother Sarah Eldridge','A life full of love.<br><em>A woman entirely herself.</em>','A family biography drawn from Sarah’s accounts and the recollections of Dasha and Verma.')}<img class="bio-reading-photo" src="${photo('img_0961').src}" alt="${e(photo('img_0961').alt)}"><div class="reading-body">${content.bio.map(s=>`<section><h2>${e(s.title)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('')}</div>${ui.source('This site edition draws from the project’s sourced biographical chapters and attributed family anecdotes. It is not a verbatim interview or the unretrieved full clean-story manuscript. Exact migration and employment dates remain under review.')}<a class="button" href="#/events">Celebrate with Sarah ${ui.icon('arrow')}</a></article>`;
  const originalLove=Sarah.pages.love;
  Sarah.pages.love=id=>id?originalLove(id):`<article class="love-reading"><header class="love-reading-cover"><p class="eyebrow">SARAH & JONAS</p><h1>The Road<br><em>Between Us</em></h1><p>An unexpected stop. A connection that became a family.</p><a class="button light" href="#/home?section=love-story">Back to the birthday weekend</a></header><div class="narrow page-bottom"><div class="story-disclosure reading-disclosure"><strong>An artistic retelling inspired by family history.</strong><p>This short site edition follows the circumstances of Sarah and Jonas’s beginning. Narrative phrasing is interpretive; it is not a verbatim account or a claim to certainty about private thoughts, dialogue, or the exact meeting date.</p></div><div class="reading-body">${SARAH_CONTENT.love.map(s=>`<section><p class="eyebrow">ACT ${s.number} · ${e(s.subtitle)}</p><h2>${e(s.title)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('')}</div>${ui.source('Family accounts place the car breakdown before work in the Arizona cotton fields and Sarah and Jonas’s connection. January 10, 1953, Nogales, Mexico is the family-designated working marriage date. The complete dramatized manuscript will require retrieval and family review before replacing this short edition.')}<a class="button" href="#/home?section=time-capsule">Explore the time capsule ${ui.icon('arrow')}</a></div></article>`;
  const day=id=>{const d=content.days.find(d=>d.day.toLowerCase()===id);if(!d)return Sarah.pages.notFound();return `<div class="wrap page-bottom"><a class="back-link" href="#/home?section=weekend">← The birthday weekend</a>${ui.heading(d.day+' · October '+Number(d.date)+', 2026',d.title,d.text)}<div class="event-grid">${SARAH_CONTENT.events.filter(ev=>d.ids.includes(ev.id)).map(Sarah.events.card).join('')}</div><p class="utility-1 notice">All times are Tucson local time. Use your family invitation for RSVP details and the private home address.</p><a class="utility-1 button outline" href="#/memories/share?event=${d.ids[0]}">Share ${d.day} photos ${ui.icon('photos')}</a></div>`;};
  function mount(section,params){
    const cleanups=[];
    const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    document.body.classList.toggle('home-experience',section==='home');
    document.querySelectorAll('[data-jump]').forEach(button=>{button.addEventListener('click',()=>document.getElementById(button.dataset.jump)?.scrollIntoView({behavior:reduced?'instant':'smooth'}));});
    if(section==='home'){
      let current=0;
      const track=document.querySelector('.era-track'),panel=document.getElementById('capsule-panel'),tabs=[...track.querySelectorAll('[data-era]')];
      const setEra=(i,focus=false)=>{current=(i+tabs.length)%tabs.length;const c=content.capsules[current];panel.className='capsule-scene '+c.theme;panel.innerHTML=capsuleMarkup(c);panel.setAttribute('aria-labelledby','era-'+c.decade);tabs.forEach((tab,n)=>{tab.setAttribute('aria-selected',String(n===current));tab.tabIndex=n===current?0:-1;});tabs[current].scrollIntoView({block:'nearest',inline:'center',behavior:reduced?'instant':'smooth'});if(focus)tabs[current].focus();if(!reduced)panel.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:450});};
      tabs.forEach((tab,i)=>tab.addEventListener('click',()=>setEra(i)));
      document.querySelectorAll('[data-era-step]').forEach(button=>button.addEventListener('click',()=>setEra(current+Number(button.dataset.eraStep))));
      track.addEventListener('keydown',event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();setEra(event.key==='Home'?0:event.key==='End'?tabs.length-1:current+(event.key==='ArrowRight'?1:-1),true);}});
      const target=params.get('section');if(target)requestAnimationFrame(()=>document.getElementById(target)?.scrollIntoView({behavior:'instant'}));
    }
    if(!reduced&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-revealed');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('will-reveal');observer.observe(el);});cleanups.push(()=>observer.disconnect());}
    return()=>{cleanups.forEach(fn=>fn());document.body.classList.remove('home-experience');};
  }
  Sarah.experience={biography,day,mount,photo};
})();
